
package cz.tieto.wheater.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-01-27T14:18:18.826+01:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "GetWeatherError", targetNamespace = "http://tieto.cz/wheater/service/types")
public class GetWeatherError extends Exception {
    
    private cz.tieto.wheater.service.types.GetWeatherError getWeatherError;

    public GetWeatherError() {
        super();
    }
    
    public GetWeatherError(String message) {
        super(message);
    }
    
    public GetWeatherError(String message, Throwable cause) {
        super(message, cause);
    }

    public GetWeatherError(String message, cz.tieto.wheater.service.types.GetWeatherError getWeatherError) {
        super(message);
        this.getWeatherError = getWeatherError;
    }

    public GetWeatherError(String message, cz.tieto.wheater.service.types.GetWeatherError getWeatherError, Throwable cause) {
        super(message, cause);
        this.getWeatherError = getWeatherError;
    }

    public cz.tieto.wheater.service.types.GetWeatherError getFaultInfo() {
        return this.getWeatherError;
    }
}
