package cz.tieto.wheater.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-01-27T14:18:18.858+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://tieto.cz/wheater/service", name = "WeatherPortTypeSOAP")
@XmlSeeAlso({cz.tieto.wheater.service.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WeatherPortTypeSOAP {

    @WebMethod(action = "/getWeather")
    @WebResult(name = "GetWeatherOutput", targetNamespace = "", partName = "GetWeatherOutput")
    public cz.tieto.wheater.service.types.GetWeatherOutput getWeather(
        @WebParam(partName = "GetWeatherInput", name = "GetWeatherInput", targetNamespace = "")
        cz.tieto.wheater.service.types.GetWeatherInput getWeatherInput
    ) throws GetWeatherError;
}
